[2024-06-24 14:28:54,395] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v03.create_postgres_table 2022-01-04T00:00:00+00:00 [queued]>
[2024-06-24 14:28:54,457] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v03.create_postgres_table 2022-01-04T00:00:00+00:00 [queued]>
[2024-06-24 14:28:54,461] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-06-24 14:28:54,462] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-06-24 14:28:54,462] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-06-24 14:28:54,517] {taskinstance.py:1063} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-01-04T00:00:00+00:00
[2024-06-24 14:28:54,533] {standard_task_runner.py:52} INFO - Started process 16743 to run task
[2024-06-24 14:28:54,569] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'create_postgres_table', '2022-01-04T00:00:00+00:00', '--job-id', '7268', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpcpgejq9m', '--error-file', '/tmp/tmp51ugpcm6']
[2024-06-24 14:28:54,577] {standard_task_runner.py:77} INFO - Job 7268: Subtask create_postgres_table
[2024-06-24 14:28:54,807] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.create_postgres_table 2022-01-04T00:00:00+00:00 [running]> on host 799b1e36e3f1
[2024-06-24 14:28:54,989] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator_v03
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2022-01-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-04T00:00:00+00:00
[2024-06-24 14:28:54,993] {postgres.py:69} INFO - Executing: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        
[2024-06-24 14:28:55,091] {taskinstance.py:1455} ERROR - The conn_id `postgres_localhost` isn't defined
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 173, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/hooks/postgres.py", line 83, in get_conn
    conn = self.connection or self.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 63, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 354, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_localhost` isn't defined
[2024-06-24 14:28:55,117] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v03, task_id=create_postgres_table, execution_date=20220104T000000, start_date=20240624T142854, end_date=20240624T142855
[2024-06-24 14:28:55,236] {local_task_job.py:146} INFO - Task exited with return code 1
