[2024-06-24 14:42:44,188] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task 2023-08-20T00:00:00+00:00 [queued]>
[2024-06-24 14:42:44,544] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task 2023-08-20T00:00:00+00:00 [queued]>
[2024-06-24 14:42:44,553] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-06-24 14:42:44,597] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-06-24 14:42:44,600] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-06-24 14:42:45,114] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): second_task> on 2023-08-20T00:00:00+00:00
[2024-06-24 14:42:45,200] {standard_task_runner.py:52} INFO - Started process 23036 to run task
[2024-06-24 14:42:45,283] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_first_dag_v5', 'second_task', '2023-08-20T00:00:00+00:00', '--job-id', '8875', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpotrds4qc', '--error-file', '/tmp/tmp7ekpmqyj']
[2024-06-24 14:42:45,359] {standard_task_runner.py:77} INFO - Job 8875: Subtask second_task
[2024-06-24 14:42:46,616] {logging_mixin.py:104} INFO - Running <TaskInstance: our_first_dag_v5.second_task 2023-08-20T00:00:00+00:00 [running]> on host 799b1e36e3f1
[2024-06-24 14:42:47,743] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2023-08-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-20T00:00:00+00:00
[2024-06-24 14:42:47,766] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2024-06-24 14:42:47,815] {bash.py:158} INFO - Running command: echo hey, I am task2 and will be running after task1!
[2024-06-24 14:42:48,092] {bash.py:169} INFO - Output:
[2024-06-24 14:42:48,185] {bash.py:173} INFO - hey, I am task2 and will be running after task1!
[2024-06-24 14:42:48,192] {bash.py:177} INFO - Command exited with return code 0
[2024-06-24 14:42:48,668] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20230820T000000, start_date=20240624T144244, end_date=20240624T144248
[2024-06-24 14:42:51,434] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-06-24 14:42:51,530] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 23036
[2024-06-24 14:42:51,557] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-24 14:42:51,568] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2024-06-24 14:42:51,694] {process_utils.py:66} INFO - Process psutil.Process(pid=23036, status='terminated', exitcode=1, started='14:42:44') (23036) terminated with exit code 1
