[2024-06-24 15:02:19,053] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v03.create_postgres_table 2022-01-05T00:00:00+00:00 [queued]>
[2024-06-24 15:02:19,080] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v03.create_postgres_table 2022-01-05T00:00:00+00:00 [queued]>
[2024-06-24 15:02:19,081] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-06-24 15:02:19,083] {taskinstance.py:1043} INFO - Starting attempt 6 of 6
[2024-06-24 15:02:19,084] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-06-24 15:02:19,115] {taskinstance.py:1063} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-01-05T00:00:00+00:00
[2024-06-24 15:02:19,126] {standard_task_runner.py:52} INFO - Started process 29296 to run task
[2024-06-24 15:02:19,140] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'create_postgres_table', '2022-01-05T00:00:00+00:00', '--job-id', '10363', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpkvhw1ej5', '--error-file', '/tmp/tmp3irqrbbf']
[2024-06-24 15:02:19,147] {standard_task_runner.py:77} INFO - Job 10363: Subtask create_postgres_table
[2024-06-24 15:02:19,294] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.create_postgres_table 2022-01-05T00:00:00+00:00 [running]> on host 799b1e36e3f1
[2024-06-24 15:02:19,486] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator_v03
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2022-01-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-05T00:00:00+00:00
[2024-06-24 15:02:19,488] {postgres.py:69} INFO - Executing: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        
[2024-06-24 15:02:19,571] {taskinstance.py:1455} ERROR - The conn_id `postgres_localhost` isn't defined
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 173, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/hooks/postgres.py", line 83, in get_conn
    conn = self.connection or self.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 63, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 354, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_localhost` isn't defined
[2024-06-24 15:02:19,581] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=dag_with_postgres_operator_v03, task_id=create_postgres_table, execution_date=20220105T000000, start_date=20240624T150219, end_date=20240624T150219
[2024-06-24 15:02:19,705] {local_task_job.py:146} INFO - Task exited with return code 1
